# Generated by Django 3.2 on 2021-12-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takoeats', '0002_auto_20211224_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, '準備中'), (2, '等待外送'), (3, '外送中'), (4, '外送員已到達目的地'), (5, '完成'), (6, '取消')], default=1),
        ),
    ]
