# Generated by Django 3.2 on 2022-01-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takoeats', '0003_auto_20220102_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
