# Generated by Django 3.2 on 2022-01-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takoeats', '0004_alter_item_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
