# Generated by Django 3.2 on 2021-12-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takoeats', '0004_auto_20211225_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='admin', max_length=16),
            preserve_default=False,
        ),
    ]
