# Generated by Django 3.2 on 2021-12-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takoeats', '0005_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
